replicaCount: 2

image:
  repository: deepiri/prismpipe
  tag: "0.2.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

config:
  host: "0.0.0.0"
  port: "8000"
  webConcurrency: "4"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 512Mi

probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 10
